### ISSUE TITLE
ПРОЧТИ ЕБАНЫЙ ИССУЕ 

### ISSUE THREAD

**Issue by smerteliko** [smerteliko/Pro-Run#5]
короче такая херня я считаю что src.css и btn.css можно никуда не девать, но нужно найти зависимость, и да то что я тебе скинул это не тупая пропись размеров, дам можно использовать динам размеры, и расчитывать с помощью них, но хз как это будет работать, а еще ты хуй

**Comment by Kraksi** [comment]
ИДИ НА                                                           Х У Й
